{
 "title": "Sample Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coherence",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coherence_score_sum/coherence_score_count",
     "legendFormat": "Coherence"
    }
   ]
  },
  {
   "title": "Relevance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "relevance_score_sum/relevance_score_count",
     "legendFormat": "Coherence"
    }
   ]
  },
  {
   "title": "Groundedness",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "groundedness_score_sum/groundedness_score_count",
     "legendFormat": "Coherence"
    }
   ]
  },
  {
   "title": "Average char length of answer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "length_score_sum/length_score_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evaluated prompts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 },
   "targets": [
    { "expr": "prompt_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OpenAI Invocation Time (msg)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "semantic_kernel_function_invocation_duration_sum",
     "legendFormat": "{{semantic_kernel_function_name}}"
    }
   ]
  },
  {
   "title": "OpenAI Tokens Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "semantic_kernel_connectors_openai_tokens_total",
     "legendFormat": "openai tokens total"
    },
    {
     "expr": "semantic_kernel_connectors_openai_tokens_completion",
     "legendFormat": "openai tokens completion"
    },
    {
     "expr": "semantic_kernel_connectors_openai_tokens_prompt",
     "legendFormat": "openai tokens prompt"
    }
   ]
  }
 ]
}